version: 0.2
run-as: root

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 442676927045.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=442676927045.dkr.ecr.us-east-1.amazonaws.com/ci-cdpipeline
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ci-cdpipeline:latest .
      - docker tag ci-cdpipeline:latest 442676927045.dkr.ecr.us-east-1.amazonaws.com/ci-cdpipeline:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 442676927045.dkr.ecr.us-east-1.amazonaws.com/ci-cdpipeline:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]'  NodeAppContainer ci-cdpipeline:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json


